### ISSUE TITLE
Cache metadata?

### ISSUE THREAD

**Issue by HughParsonage** [ropenscilabs/datagovau#7]
`search_data` is too slow for interactive use:

```
> system.time(search_data("name:fire"))
   user  system elapsed 
   0.06    0.00   12.43 
```

The performance could be improved by caching the metadata:

* in each package release
* after the first invocation in a session
* if the user requests it

The pros and cons of the first are obvious: it would be more reliable and faster, but won't return metadata that forms post-release. Frequent releases would limit the downside, and I think it's my preferred method.

**Comment by ellisp** [comment]
Sounds good.  I think the WDI package does something similar, you probably know examples too - if you could do this would be helpful (BTW maybe pull down from GitHub first as we've changed pretty much everything quite substantially over the last hour or so).
